name: Print Workflow Data
description: "prints select github context for debugging purposes"

branding:
  color: 'green'
  icon: 'bar-chart-2'

inputs:
  caller-inputs:
    description: '`caller-inputs: {{ toJSON(inputs) }}`'
    required: false
    default: ''
  caller-needs:
    description: '`caller-needs: {{ toJSON(needs) }}`'
    required: false
    default: ''
  caller-vars:
    description: 'pass via `caller-vars: {{ toJSON(vars) }}` (generally safe unless secrets have been mismanaged)'
    required: false
    default: ''
  extras:
    description: 'pass additional values to print here, ideally in toJSON(...) format'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Print Workflow Data
      shell: bash
      continue-on-error: true
      env:
        MATRIX_CONTEXT: ${{ matrix && toJSON(matrix) || 'n/a' }}
        JOB_CONTEXT: ${{ toJSON(job) }}
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
        CALLER_INPUTS: ${{ inputs.caller-inputs != '' && inputs.caller-inputs || 'n/a' }}
        CALLER_NEEDS: ${{ inputs.caller-needs != '' && inputs.caller-needs || 'n/a' }}
        CALLER_VARS: ${{ inputs.caller-vars != '' && inputs.caller-vars || 'n/a' }}
        EXTRAS: ${{ inputs.extras != '' && inputs.extras || 'n/a' }}
        DEFAULT_BRANCH: ${{ github.event && github.event.repository && github.event.repository.default_branch }}
      run: |
        print_section() {
          local title="$1"
          local body="$2"
          local color=92 # bright green
          local bar_len=$(( ${#title} + 2 ))
          echo -e "\e[1;${color}m┌$(printf '─%.0s' $(seq 1 $bar_len))┐\e[0m"
          echo -e "\e[1;${color}m│ ${title} │\e[0m"
          echo -e "\e[1;${color}m└$(printf '─%.0s' $(seq 1 $bar_len))┘\e[0m"
          echo -e "$body"
        }
        
        github_context_body=$(cat <<EOF
        github.actor            : ${{ github.actor }}
        github.triggering_actor : ${{ github.triggering_actor }}
        github.workflow         : ${{ github.workflow }}
        github.workflow_ref     : ${{ github.workflow_ref }}
        github.run_id           : ${{ github.run_id }}
        github.run_number       : ${{ github.run_number }}
        github.run_attempt      : ${{ github.run_attempt }}
        github.event_name       : ${{ github.event_name }}
        github.event.action     : ${{ github.event.action }}
        github.base_ref         : ${{ github.base_ref }}
        github.head_ref         : ${{ github.head_ref }}
        is_default_branch       : ${{ github.ref_name == env.DEFAULT_BRANCH }}
        is_default_target       : ${{ github.base_ref == env.DEFAULT_BRANCH }}
        github.ref              : ${{ github.ref }}
        github.ref_name         : ${{ github.ref_name }}
        github.sha              : ${{ github.sha }}
        EOF
        )
        
        print_section "github context" "$github_context_body"
        print_section "matrix context" "$MATRIX_CONTEXT"
        print_section "job context" "$JOB_CONTEXT"
        print_section "runner context" "$RUNNER_CONTEXT"
        print_section "caller inputs" "$CALLER_INPUTS"
        print_section "caller needs" "$CALLER_NEEDS"
        print_section "caller vars" "$CALLER_VARS"
        print_section "extras" "$EXTRAS"
