name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: hwrok/print-workflow-data@v1

      - name: checkout
        uses: actions/checkout@v6

      - name: pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: node
        uses: actions/setup-node@v6.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: pnpm install
        id: install-deps
        run: pnpm install

      - name: check - tests
        if: always() && steps.install-deps.outcome == 'success'
        run: pnpm test

      - name: check - formatting
        if: always() && steps.install-deps.outcome == 'success'
        run: pnpm format

      - name: check - spelling
        if: always() && steps.install-deps.outcome == 'success'
        run: pnpm spellcheck
