name: smoke-test

on:
  workflow_run:
    workflows: [release]
    types: [completed]

jobs:
  smoke-test:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: print workflow data (smoke-test)
        uses: hwrok/print-workflow-data@v1
